copyright = "© Jeremy Lewi"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Gallery"

[params]
  defaultTheme = "dark"
  description = "Dogs of Crestmoor"
  title = "Crestmoor Woofpack"
  [params.author]
    email = "jeremy@lewi.us"
    name = "Jeremy Lewi"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    #instagram = "https://www.instagram.com/"
    github = "https://github.com/jlewi/woofpack/"
    #youtube = "https://www.youtube.com/"
    email = "mailto:jeremy@lewi.us"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/jlewi/woofpack/"
    weight = 3

[services]
  [services.rss]
    limit = 100
